dubbo:
  application:
    name: consumer-demo
  registry:
    address: 192.168.7.1:2181
    protocol: zookeeper
    check: true # true注册订阅失败时报错
  consumer:
    timeout: 3000 # 调用服务超时时间  reference > service > consumer > provider
    retries: 2 # 不包含第一次调用
    check: true # 启动时检查提供者是否存在，true报错，false忽略
    loadbalance: roundrobin
server:
  port: 8001