dubbo:
  application:
    name: provider-demo
  protocol:
    name: dubbo
    port: 20880 #如果部署多台 端口不同重复
    status: server
  registry:
    address: 192.168.7.1:2181
    protocol: zookeeper
server:
  port: 7001  #如果部署多台 端口不同重复