dubbo:
  application:
    name: provider-demo
  protocol:
    name: dubbo
    port: 20880
    status: server
  registry:
    address: 10.9.216.1:2181,10.9.216.14:2181,10.9.217.3:2181
    protocol: zookeeper
server:
  port: 7001